micronaut:
  application:
    name: propostaGrpc
datasources:
  default:
    url: jdbc:mysql://localhost:3306/proposta_grpc?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    schema-generate: CREATE_DROP
    dialect: MYSQL
jpa.default.properties.hibernate.hbm2ddl.auto: update

url:
  solicitacao: ${URL_SOLICITACAO:`http://localhost:9999/api`}
feign:
  url: ${URL_CARTAO:`http://localhost:8888/api`}
